### ISSUE TITLE
Current alpine images are missing shared library libsystemd.so.0

### ISSUE THREAD

**Issue by Elegant996** [goofball222/unifi#107]
When deploying currently alpine images (7.2.95, 7.3-beta, etc.) the `libsystemd.so.0` library is missing.

```
unifi java.lang.UnsatisfiedLinkError: /usr/lib/unifi/lib/native/Linux/x86_64/libubnt_sdnotify_jni.so: Error loading shared library libsystemd.so.0: No such file or directory (needed by /usr/lib/unifi/lib/native/Linux/x86_64/libubnt_sdnotify_jni.so)
unifi     at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_345]
unifi     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946) ~[?:1.8.0_345]
unifi     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1828) ~[?:1.8.0_345]
unifi     at java.lang.Runtime.load0(Runtime.java:810) ~[?:1.8.0_345]
unifi     at java.lang.System.load(System.java:1088) ~[?:1.8.0_345]
unifi     at com.ubnt.sdnotify.SDNotify.notify(Unknown Source) ~[ace.jar:?]
unifi     at com.ubnt.sdnotify.oOOO.Ó00000(Unknown Source) ~[ace.jar:?]
unifi     at com.ubnt.sdnotify.oOOO.o00000(Unknown Source) ~[ace.jar:?]
unifi     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
unifi     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
unifi     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
unifi     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
unifi     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:88) ~[guava-31.0.1-jre.jar:?]
unifi     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:145) ~[guava-31.0.1-jre.jar:?]
unifi     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:73) ~[guava-31.0.1-jre.jar:?]
unifi     at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.0.1-jre.jar:?]
unifi     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-31.0.1-jre.jar:?]
unifi     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:109) ~[guava-31.0.1-jre.jar:?]
unifi     at com.google.common.eventbus.EventBus.post(EventBus.java:267) ~[guava-31.0.1-jre.jar:?]
unifi     at com.ubnt.service.system.event.O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Ò00000(Unknown Source) ~[ace.jar:?]
unifi     at com.ubnt.net.OoOO.o00000(Unknown Source) ~[ace.jar:?]
unifi     at com.ubnt.net.OoOO.oO0000(Unknown Source) ~[ace.jar:?]
unifi     at com.ubnt.service.Object.ÖÔ0000(Unknown Source) ~[ace.jar:?]
unifi     at com.ubnt.ace.Launcher.main(Unknown Source) ~[ace.jar:?]

```

**Comment by goofball222** [comment]
This is an expected error since Alpine Linux doesn't use/have systemd by default. The error appears to be entirely cosmetic in my experience so far running the Alpine-based container. Please report back if you find this is causing other issues outside of the loading error at startup.
