### ISSUE TITLE
Failure upgrading to 7.4.156

### ISSUE THREAD

**Issue by TheQue42** [goofball222/unifi#115]
## Reporting bugs/issues

Been running with a separate mongo db (:5)  and 7.3 without issues for a long time. Upgrading to 7.4 fails, and all attempts to change external mongodb to either 3.6, 4, 6, 7 fails, even with a fresh install (of any container)

On OpenSuse 15.4, Docker version 20.10.23-ce, build 6051f1429

```
#> docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 12
  Running: 10
  Paused: 0
  Stopped: 2
 Images: 29
 Server Version: 20.10.23-ce
 Storage Driver: btrfs
  Build Version: Btrfs v4.15
  Library Version: 102
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc version: v1.1.5-0-gf19387a6bec4
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.21-150400.24.63-default
 Operating System: openSUSE Leap 15.4
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.34GiB
 Name: vimes
 ID: 5DRI:SUAX:DTXQ:42MZ:E34J:BOZD:MI5G:VUQC:2ZQL:ZPRN:UB5X:5C5A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Log from the start of unifi:

```
[2023-06-03 09:35:20,605] <launcher> INFO  tomcat - Adding basic REST API support during the startup
[2023-06-03 09:35:21,033] <launcher> INFO  system - Tomcat startup took 831ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.65.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2023-06-03 09:35:21,047] <launcher> INFO  tomcat - Adding basic REST API support during the startup
[2023-06-03 09:35:24,736] <launcher> INFO  db     - Starting database service initialization...
[2023-06-03 09:35:24,736] <launcher> INFO  db     - waiting for db connection...
[2023-06-03 09:35:25,237] <launcher> INFO  db     - Connecting to mongodb://mongodb:27017/unifi
[2023-06-03 09:35:25,327] <launcher> INFO  db     - db connection established...
[2023-06-03 09:35:25,384] <launcher> INFO  db     - db connected (v5.0.18@mongodb://mongodb:27017/unifi)
[2023-06-03 09:35:25,386] <launcher> WARN  db     - Unable to ensure mongodb features version to 3.6: class org.bson.Document cannot be cast to class java.lang.String (org.bson.Document is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
[2023-06-03 09:35:25,459] <launcher> INFO  db     - Database service initialized...
[2023-06-03 09:35:25,466] <launcher> INFO  system - ======================================================================
[2023-06-03 09:35:25,467] <launcher> INFO  system - UniFi 7.4.156 (build atag_7.4.156_21011 - release/release) is started
[2023-06-03 09:35:25,467] <launcher> INFO  system - Environment: UniFi-OS[false], UniFi-Cloud[false], UniFi-MongoService[false]
[2023-06-03 09:35:25,467] <launcher> INFO  system - ======================================================================
[2023-06-03 09:35:25,467] <launcher> INFO  system - BASE dir:/usr/lib/unifi
[2023-06-03 09:35:25,468] <launcher> INFO  system - Current System IP: 172.18.0.3
[2023-06-03 09:35:25,468] <launcher> INFO  system - Hostname: e7740cacab32
[2023-06-03 09:35:25,469] <launcher> INFO  system - ubic.env: stage
[2023-06-03 09:35:26,541] <launcher> WARN  AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ubnt.net.SpringConfig]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.ubnt.net.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[2023-06-03 09:35:26,544] <launcher> ERROR ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ubnt.net.SpringConfig]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.ubnt.net.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:311)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4766)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at com.ubnt.net.B.Oo0000(Unknown Source)
        at com.ubnt.net.B.Òo0000(Unknown Source)
        at com.ubnt.service.O0OO.öÓ0000(Unknown Source)
        at com.ubnt.ace.Launcher.Õ00000(Unknown Source)
        at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class com.ubnt.net.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:162)
        at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:403)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:326)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:600)
        ... 21 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.ubnt.net.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:459)
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:151)
        ... 25 common frames omitted
Caused by: java.lang.NoClassDefFoundError: springfox/documentation/spring/web/plugins/Docket
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
        ... 27 common frames omitted
Caused by: java.lang.ClassNotFoundException: springfox.documentation.spring.web.plugins.Docket
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 31 common frames omitted
[2023-06-03 09:35:26,547] <launcher> ERROR [/]    - Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ubnt.net.SpringConfig]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.ubnt.net.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610)
```
Since the example for using docker-compose still doesnt indicate that I need to restrict the mongdo db-version to a specific version, I'm still not clear on which version I am supposed to use, but :5 has been working fine for 7.3 and it feels strange that a newer version would need an OLDER version??

**Comment by goofball222** [comment]
I'm using mongodb v5.0.19, and v5.0.18 prior to that without issue.

One thing I see different between your setup and mine is:
```unifi    | [2023-07-18 01:11:47,449] <launcher> INFO  system - ubic.env: prod```

Are you running the Debian, Ubuntu, or Alpine version of the container?

**Comment by TheQue42** [comment]
> I'm using mongodb v5.0.19, and v5.0.18 prior to that without issue.
> 
> One thing I see different between your setup and mine is: `unifi | [2023-07-18 01:11:47,449] <launcher> INFO system - ubic.env: prod`
> 
> Are you running the Debian, Ubuntu, or Alpine version of the container?

I tried all three with what I could see, similar results. Finally, I tried a version without the separate mongo-db, and then it worked. Havent had time to go back since then :-/
