### ISSUE TITLE
switching to docker-compose with separate mongo fails

### ISSUE THREAD

**Issue by cardoe** [goofball222/unifi#26]
So I'm attempting to take my system that's run with:
```
docker run \
    --name unifi \
    -d \
    --restart always \
    -p 3478:3478/udp \
    -p 6789:6789 \
    -p 8080:8080 \
    -p 8443:8443 \
    -p 8880:8880 \
    -p 8843:8843 \
    -p 10001:10001/udp \
    -v /var/lib/unifi/cert:/usr/lib/unifi/cert \
    -v /var/lib/unifi/data:/usr/lib/unifi/data \
    -v /var/lib/unifi/logs:/usr/lib/unifi/logs \
    -v /var/lib/unifi/supervisor:/var/log/supervisor \
    goofball222/unifi:release-5.8.30
```

to one started with Docker Compose. I'm attempting to get ahead of the coming changes to split out the mongo instance. The config I'm using is:

```
version: '3'

services:
  mongo:
    image: mongo:3.4
    container_name: unifidb
    restart: unless-stopped
    volumes:
      - /var/lib/unifi/data/db:/data/db

  unifi:
    image: goofball222/unifi:unifi58-debian-nomongo
    container_name: unifi
    restart: unless-stopped
    links:
      - mongo
    ports:
      - 3478:3478/udp
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 10001:10001/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/unifi/cert:/usr/lib/unifi/cert
      - /var/lib/unifi/data:/usr/lib/unifi/data
      - /var/lib/unifi/logs:/usr/lib/unifi/logs
    environment:
      - DB_MONGO_LOCAL=false
      - DB_MONGO_URI=mongodb://mongo:27017/unifi
      - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
      - TZ=America/Chicago
      - UNIFI_DB_NAME=unifi
```

I started with the recommended Docker Compose and changed the following:
- adjusted the paths outside of the container to match where I have them
- adjusted `TZ` (not sure if this is correct) but my system runs America/Chicago so I assume its got that inside the container currently.
- uncommented out all the ports to map them in
- pinned mongo to 3.4 due to the comments I've read in the Unifi forums about needing to stick to 3.4.x
- pinned your container to unifi58-debian-nomongo since I believe that's the closest thing to what I was previously running

I'm starting everything with `docker-compose -f unifi.yml up -d` and this is is the log file I get from `docker logs unifi`:

```
[2018-09-22 18:29:57,758] <docker-entrypoint> INFO - Entrypoint script version 1.0.6
[2018-09-22 18:29:57,764] <docker-entrypoint> INFO - Entrypoint functions version 1.0.6
[2018-09-22 18:29:57,775] <docker-entrypoint> INFO - Entrypoint running with UID 0 (root)
[2018-09-22 18:29:57,796] <docker-entrypoint> INFO - GID/UID for unifi are unchanged: GID=999, UID=999
[2018-09-22 18:29:57,802] <docker-entrypoint> INFO - Checking system.properties setup for container
[2018-09-22 18:29:57,824] <docker-entrypoint> INFO - Existing '/usr/lib/unifi/data/system.properties' found, ensuring container mode options are enabled
[2018-09-22 18:29:57,852] <docker-entrypoint> WARN - Custom SSL: missing '/usr/lib/unifi/cert/privkey.pem'
[2018-09-22 18:29:57,866] <docker-entrypoint> WARN - Custom SSL: missing '/usr/lib/unifi/cert/fullchain.pem'
[2018-09-22 18:29:57,871] <docker-entrypoint> WARN - Custom SSL: certificate import was NOT performed
[2018-09-22 18:29:57,881] <docker-entrypoint> INFO - Ensuring permissions are correct before continuing - 'chown -R unifi:unifi /usr/lib/unifi'
[2018-09-22 18:29:57,886] <docker-entrypoint> INFO - Running recursive 'chown' on Docker overlay2 storage is **really** slow. This may take a bit.
[2018-09-22 18:29:58,179] <docker-entrypoint> INFO - Use gosu to drop privileges and start Java/UniFi as GID=999, UID=999
[2018-09-22 18:29:58,186] <docker-entrypoint> EXEC - gosu unifi:unifi /usr/bin/java  -Xmx1024M -Dunifi.datadir=/usr/lib/unifi/data -Dunifi.logdir=/usr/lib/unifi/logs -Dunifi.rundir=/usr/lib/unifi/run -Djava.awt.headless=true -Dfile.encoding=UTF-8 -jar /usr/lib/unifi/lib/ace.jar start
[2018-09-22 18:29:59,249] <launcher> INFO  system - ======================================================================
[2018-09-22 18:29:59,250] <launcher> INFO  system - UniFi 5.8.30 (build atag_5.8.30_11076 - release) is started
[2018-09-22 18:29:59,250] <launcher> INFO  system - ======================================================================
[2018-09-22 18:29:59,251] <launcher> INFO  system - BASE dir:/usr/lib/unifi
[2018-09-22 18:29:59,255] <launcher> INFO  system - Current System IP: 192.168.1.4
[2018-09-22 18:29:59,256] <launcher> INFO  system - Hostname: d345d02673c3
[2018-09-22 18:31:02,805] <generate-report> WARN  system - cannot update to version
java.lang.IllegalArgumentException
	at org.bson.types.ObjectId.isValid(ObjectId.java:92)
	at org.bson.types.ObjectId.parseHexString(ObjectId.java:549)
	at org.bson.types.ObjectId.<init>(ObjectId.java:240)
	at com.ubnt.service.B.OOoo.super(Unknown Source)
	at com.ubnt.service.N.A.Òo0000(Unknown Source)
	at com.ubnt.service.N.A.ÕÕ0000(Unknown Source)
	at com.ubnt.service.N.A.ØöO000(Unknown Source)
	at com.ubnt.service.N.A.privateprivate(Unknown Source)
	at com.ubnt.service.B.ooOO$2.run(Unknown Source)
	at com.ubnt.ace.ooOO$_O0.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I've tried the alpine image as well and get the same results. I'm sure its something obvious that I'm missing.

**Comment by goofball222** [comment]
What do the docker logs show for the mongo container when it starts (IE: `docker logs unifidb`)? Depending on which mongodb version the database files you're using are from they may need to be upgraded before mongo will start. - https://docs.mongodb.com/manual/release-notes/3.4-upgrade-standalone/ - "To upgrade from a version earlier than the 3.2-series, you must successively upgrade major releases until you have upgraded to 3.2-series. For example, if you are running a 3.0-series, you must upgrade first to 3.2 before you can upgrade to 3.4."

***Make a data backup before messing with mongodb upgrades so you can revert if needed!***

It may be easier to export a .unf backup of your existing controller and then set up a new unifi and mongodb container from scratch with clean volumes, then restore from that .unf. YMMV.

**Comment by cardoe** [comment]
So apologies for the delay. I specifically pinned to Mongo 3.4 because that's what I had believed you used in the v5.8.30 UniFi container. I went into the running container with `docker exec -it unifi /bin/bash` and got the following:
```
mongod --version
db version v3.4.17
git version: 7c14a47868643bb691a507a92fe25541f998eca4
OpenSSL version: OpenSSL 1.0.2l  25 May 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64
```
My goal was to attempt to match Mongo versions to avoid exactly what you pointed out.

**Comment by cardoe** [comment]
```
docker logs unifidb
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=33ac36b25cc8
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] db version v3.4.17
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] git version: 7c14a47868643bb691a507a92fe25541f998eca4
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] modules: none
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] build environment:
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten]     distmod: debian81
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-12-15T16:12:06.334+0000 I CONTROL  [initandlisten] options: {}
2018-12-15T16:12:06.337+0000 I -        [initandlisten] Detected data files in /data/db created by the 'mmapv1' storage engine, so setting the active storage engine to 'mmapv1'.
2018-12-15T16:12:06.362+0000 I STORAGE  [initandlisten]
2018-12-15T16:12:06.362+0000 I STORAGE  [initandlisten] ** WARNING: Readahead for /data/db is set to 2048KB
2018-12-15T16:12:06.362+0000 I STORAGE  [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
2018-12-15T16:12:06.362+0000 I STORAGE  [initandlisten] **          http://dochub.mongodb.org/core/readahead
2018-12-15T16:12:06.369+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
2018-12-15T16:12:06.369+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2018-12-15T16:12:06.600+0000 I JOURNAL  [durability] Durability thread started
2018-12-15T16:12:06.600+0000 I JOURNAL  [journal writer] Journal writer thread started
2018-12-15T16:12:06.682+0000 I CONTROL  [initandlisten]
2018-12-15T16:12:06.682+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-12-15T16:12:06.682+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-12-15T16:12:06.682+0000 I CONTROL  [initandlisten]
2018-12-15T16:12:07.682+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-12-15T16:12:07.685+0000 I NETWORK  [thread1] waiting for connections on port 27017
2018-12-15T16:12:11.967+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:53766 #1 (1 connection now open)
2018-12-15T16:12:11.971+0000 I NETWORK  [conn1] received client metadata from 172.19.0.3:53766 conn1: { driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.15.0-32-generic" }, platform: "Java/Oracle Corporation/1.8.0_171-8u171-b11-1~bpo8+1-b11" }
2018-12-15T16:12:11.984+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:53768 #2 (2 connections now open)
2018-12-15T16:12:11.985+0000 I NETWORK  [conn2] received client metadata from 172.19.0.3:53768 conn2: { driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.15.0-32-generic" }, platform: "Java/Oracle Corporation/1.8.0_171-8u171-b11-1~bpo8+1-b11" }
2018-12-15T16:12:12.754+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:53770 #3 (3 connections now open)
2018-12-15T16:12:12.754+0000 I NETWORK  [conn3] received client metadata from 172.19.0.3:53770 conn3: { driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.15.0-32-generic" }, platform: "Java/Oracle Corporation/1.8.0_171-8u171-b11-1~bpo8+1-b11" }
2018-12-15T16:12:12.756+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:53772 #4 (4 connections now open)
2018-12-15T16:12:12.756+0000 I NETWORK  [conn4] received client metadata from 172.19.0.3:53772 conn4: { driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.15.0-32-generic" }, platform: "Java/Oracle Corporation/1.8.0_171-8u171-b11-1~bpo8+1-b11" }
2018-12-15T16:12:23.034+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:53774 #5 (5 connections now open)
2018-12-15T16:12:23.034+0000 I NETWORK  [conn5] received client metadata from 172.19.0.3:53774 conn5: { driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.15.0-32-generic" }, platform: "Java/Oracle Corporation/1.8.0_171-8u171-b11-1~bpo8+1-b11" }
```

**Comment by cardoe** [comment]
So I've quite literally matched the same MongoDB version. And I'm using the unifi58-debian-nomongo container for Unifi with the same version as the original unifi container.

**Comment by sprocktech** [comment]
@cardoe, in your unifidb logs there is this line:

`2018-12-15T16:12:06.337+0000 I -        [initandlisten] Detected data files in /data/db created by the 'mmapv1' storage engine, so setting the active storage engine to 'mmapv1'.`

For this reason alone, I would restore from a .unf backup like @goofball222 suggested because that would effectively perform an [upgrade to WiredTiger](https://help.ubnt.com/hc/en-us/articles/360006634094-UniFi-Network-Controller-Repairing-Database-Issues-on-the-UniFi-Controller#6).

**Comment by cardoe** [comment]
Logging into each device and running `set-inform http://controller-ip:8080/inform` solved the adopting loop. Likely it made it accept the SSH host key?

**Comment by sprocktech** [comment]
Using set-inform would've been my suggestion. The set-inform process doesn't deal with SSH host keys, that's config level stuff, it does exchange an encryption key though. I'm curious, where did you see mention about the single container going away in favor of split containers?

**Comment by goofball222** [comment]
@sprocktech there is a warning in the startup script that fires when running as a multi-process container (DB and UniFi in one):

```
WARN - One or more of: 'DB_MONGO_LOCAL', 'DB_MONGO_URI', 'STATDB_MONGO_URI', or 'UNIFI_DB_NAME' is unset.
WARN - In the future you should consider running UniFi on Docker with an external Mongo DB instance defined.
WARN - *** Please check the README.md and examples at https://github.com/goofball222/unifi ***
```

The monolithic Debian 8 based image with integrated Mongo will continue to exist until it is unsupportable, IE: UBNT devs make breaking changes to where the UniFi software will no longer run, or a major unfixed security issue is found in the Debian 8 base.

Beyond that, best practice for Docker is that each container only runs a single process/service. Externalizing the Mongo database service does that here. It also reduces the build complexity and increases the container flexibility to allow for everything from simple home deployments on a NAS to multi-node HA Docker host/swarm configurations all pointing back to a Mongo node/cluster.

@cardoe Looks like this is now resolved. I'm going to close this issue out.
